### ISSUE TITLE
Dataset error

### ISSUE THREAD

**Issue by UrwLee** [Tsingularity/PoseNorm_Fewshot#2]
The link of  OID-Aircraft seems to be invalidate, can you offer some other address?

**Comment by Tsingularity** [comment]
Hi, thanks for spotting this issue and I also just noticed that their dataset webpage is down. 

Just for your reference, this is the [paper](https://www.robots.ox.ac.uk/~karen/pdf/vedaldi14understanding.pdf) for the OID dataset. I'll email the authors and let them know about the webpage issue. Let's see how they gonna respond. If they don't reply or fix it within a few days, I'll try to upload my copy of their dataset to google drive and update the readme. I'll also keep this thread updated if there's anything new.

Thanks again!

**Comment by Tsingularity** [comment]
Hi, I just uploaded one copy of the OID dataset to this google drive [link](https://drive.google.com/file/d/10vKcoS6-JFEpioD_FStJZbWknFCfPOnU/view?usp=sharing), and also updated the readme file. Feel free to let me know if there's anything else I can help with.

Thanks!
